site_name: dustland
site_url: https://dustball.top/
site_author: dustball
site_description: 奇怪论调，满口放炮

theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  logo: assets/logo.png
  palette:

    #亮色
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    #暗色
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search

nav:
  - 首页: posts/index.md
  - 中国象棋: 
    - posts/中国象棋/index.md
    - 布局:
      - posts/中国象棋/布局/布局-七星剑.md
      - posts/中国象棋/布局/布局-巡河车.md
      - posts/中国象棋/布局/布局-疑形与攻击.md
      - posts/中国象棋/布局/布局-顺炮五六炮.md
      - posts/中国象棋/布局/布局-顺炮过河车.md
      - posts/中国象棋/布局/布局-五六炮对屏风马.md
    - 复盘:
      - posts/中国象棋/复盘/复盘-2026.4.md
      - posts/中国象棋/复盘/复盘-2025.10.md
      - posts/中国象棋/复盘/复盘-2025.9.md
      - posts/中国象棋/复盘/复盘-2025.8.md
      - posts/中国象棋/复盘/复盘-2025.6.md
      - posts/中国象棋/复盘/复盘-2025.5.md
      - posts/中国象棋/复盘/复盘-顺炮直车对横车.md
      - posts/中国象棋/复盘/复盘-中炮过河车互进七兵对屏风马左马盘河.md
  - CSAPP:
    - posts/CSAPP/index.md
    - posts/CSAPP/C++运行时多态.md
    - posts/CSAPP/coredump.md
    - posts/CSAPP/ELF.md
    - posts/CSAPP/EXE.md
    - posts/CSAPP/IEEE754.md
    - posts/CSAPP/动态链接.md
    - posts/CSAPP/虚拟内存.md
    - posts/CSAPP/链接.md
  - 模糊测试:
    - posts/模糊测试/index.md
    - AFL:
      - posts/模糊测试/AFL/[AFL I]overview.md
      - posts/模糊测试/AFL/[AFL II]whitepaper.md
      - posts/模糊测试/AFL/[AFL III]afl-tmin.md
      - posts/模糊测试/AFL/[AFL IV]afl-showmap.md
      - posts/模糊测试/AFL/[AFL V]afl-analyze.md
      - posts/模糊测试/AFL/[AFL VI]afl-gcc.md
    - Syzkaller:
      - posts/模糊测试/Syzkaller/[syzkaller I]overview.md
      - posts/模糊测试/Syzkaller/[syzkaller II]syz-extract.md
      - posts/模糊测试/Syzkaller/[Syzkaller III]syzlang.md
      - posts/模糊测试/Syzkaller/[Syzkaller IV]syz-sysgen.md
      - posts/模糊测试/Syzkaller/[Syzkaller V]syz-executor.md
      - posts/模糊测试/Syzkaller/[Syzkaller VI]syz-manager.md
  - 程序调试:
    - posts/程序调试/index.md
    - posts/程序调试/gdb命令速览.md
    - posts/程序调试/gdb调试器.md
    - posts/程序调试/内核调试.md
    - posts/程序调试/调试.md
    - posts/程序调试/调试Glibc.md
  - 趁手工具:
    - posts/趁手工具/index.md
    - posts/趁手工具/wsl.md