site_name: dustland
site_url: https://dustball.top/
site_author: dustball
site_description: 奇怪论调，满口放炮

theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: LXGW WenKai
    code: JetBrains Mono
  palette:

    #亮色
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    #暗色
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips

extra:
  author: dustball
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeutschBall

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.tilde

extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - section-index
  - document-dates
  - statistics
  - tags
  - mkdocs-audio

nav:
  - 首页👋: index.md
  - 战术标签🏷️: tags.md
  - 对局复盘⚔️:
    - posts/复盘/index.md
    - 2026 业7+ 👦:
      - June:
        - posts/复盘/2026/June/中炮盘头马有时可以弃马保中兵@2026.6.22.md
        - posts/复盘/2026/June/先锋马除了换中卒还可以配合五七炮@2026.6.14.md
        - posts/复盘/2026/June/中炮两头蛇不出车应对对小列炮@2026.6.13.md
        - posts/复盘/2026/June/中炮盘头马何时冲中兵@2026.6.10.md
        - posts/复盘/2026/June/注意士角炮打串@2026.6.6.md
        - posts/复盘/2026/June/攻击臭棋乱飞相@2026.6.6.md
        - posts/复盘/2026/June/如何应对过河车压马@2026.6.5.md
        - posts/复盘/2026/June/中炮对拐角马象位车@2026.6.1.md
        - posts/复盘/2026/June/仙人指路对卒底炮红右中炮黑跳正马@2026.6.1.md
      - August:
        - posts/复盘/2026/August/中炮巡河炮快攻龟背炮.md
      - May:
        - posts/复盘/2026/May/顺炮缓开车对直车@2026.5.30.md
        - posts/复盘/2026/May/过宫炮对中炮横车盘头马@2026.5.29.md
        - posts/复盘/2026/May/中炮对屏风马@2026.5.29.md
        - posts/复盘/2026/May/顺炮直车五六炮对横车@2026.5.27.md
        - posts/复盘/2026/May/中炮进三兵对左炮封车转半途列炮@2026.5.27.md
        - posts/复盘/2026/May/中炮对士角炮转单提马@2026.5.26.md
        - posts/复盘/2026/May/顺炮叶底藏花@2026.5.26.md
        - posts/复盘/2026/May/中炮对过宫炮@2026.5.24.md
        - posts/复盘/2026/May/顺炮直车过河对横车@2026.5.25.md
        - posts/复盘/2026/May/顺炮直车过河对横车@2026.5.24.md
        - posts/复盘/2026/May/中炮对进左马桥头堡@2026.5.21.md
        - posts/复盘/2026/May/中炮对屏风马@2026.5.18.md
        - posts/复盘/2026/May/飞相对中炮@2026.5.17.md
        - posts/复盘/2026/May/起马局对进卒@2026.5.13.md
        - posts/复盘/2026/May/中炮对过宫炮@2026.5.10.md
        - posts/复盘/2026/May/仙人指路对起马局@2026.5.7.md
      - April:
        - posts/复盘/2026/April/复盘-2026.4.md
        - posts/复盘/2026/April/中炮对五七列炮@2026.4.28.md
        - posts/复盘/2026/April/仙人指路对起马局@2026.4.12.md
        - posts/复盘/2026/April/中炮对反宫马@2026.4.12.md
        - posts/复盘/2026/April/顺炮直车五六炮对横车@2026.4.3.md
        - posts/复盘/2026/April/中炮对单提马@2026.4.3.md
      - March:
        - posts/复盘/2026/March/过宫炮对中炮@2026.3.27.md
    - 2025 业3~业7 👶:
      - 10月:
        - posts/复盘/2025/复盘-2025.10.md
      - 9月:
        - posts/复盘/2025/复盘-2025.9.md
      - 8月:
        - posts/复盘/2025/复盘-2025.8.md
      - 6月:
        - posts/复盘/2025/复盘-2025.6.md
      - 5月:
        - posts/复盘/2025/复盘-2025.5.md
        - posts/复盘/2025/复盘-顺炮直车对横车.md
      - 4月:
        - posts/复盘/2025/复盘-中炮过河车互进七兵对屏风马左马盘河.md

  - 局部常型🏦:
    - posts/局部常型/index.md
    - 炮着:
      - posts/局部常型/炮着/index.md
      - posts/局部常型/炮着/抢占布置线@2026.5.12.md
    - 车着:
      - posts/局部常型/车着/index.md
      - posts/局部常型/车着/七星剑.md
      - posts/局部常型/车着/三步雷.md

  - 局势判断🧐:
    - posts/局势判断/index.md
    - 中炮对列炮: posts/局势判断/中炮对列炮.md

  - 布局棋理💡:
    - posts/布局棋理/index.md
    - 定式📖:
      - 中炮对屏风马:
        - posts/布局棋理/定式/五六炮对屏风马.md
      - 顺炮:
        - posts/布局棋理/定式/顺炮过河车.md
        - posts/布局棋理/定式/顺炮五六炮.md
      - 仙人指路:
        - posts/布局棋理/定式/仙人指路对兵局.md
    - 疑形⚠️:
      - 中炮对屏风马:
        - posts/布局棋理/疑形/中炮对屏风马布局疑形总结.md
      - 顺炮:
        - posts/布局棋理/疑形/顺炮布局疑型总结.md
      - 仙人指路:
        - posts/布局棋理/疑形/仙人指路黑方为什么不能走右中炮@2026.6.10.md
        - posts/布局棋理/疑形/仙人指路对卒底炮为什么红棋不能走左中炮@2026.6.1.md
        - posts/布局棋理/疑形/仙人指路布局疑形总结.md
      - 列炮:
        - posts/布局棋理/疑形/列炮布局疑型总结.md
      - 通论:
        - posts/布局棋理/疑形/疑形与攻击.md